extends Node

var world_selected: String = ""


const PACKEDSCENES = {
	"Guns": {
		"Futuristic Chicago": preload("res://Scenes/Player/Guns/futuristic_chicago.tscn"), # Corrected file path
		"Rocket Launcher": preload("res://Scenes/Player/Guns/rocket_launcher.tscn"), # Corrected file path
		"Desert Sniper": preload("res://Scenes/Player/Guns/desert_sniper.tscn"),
		"M45": preload("res://Scenes/Player/Guns/m_45.tscn"),
		"F547": preload("res://Scenes/Player/Guns/f_547.tscn"),
		"K6554": preload("res://Scenes/Player/Guns/k_6554.tscn"),
		"RRR7": preload("res://Scenes/Player/Guns/rrr_7.tscn"),
		"T58": preload("res://Scenes/Player/Guns/t_58.tscn"),
		"G65": preload("res://Scenes/Player/Guns/g_65.tscn")
	},	
	"Projectiles": {
		"projectile_for_player": preload("res://Scenes/Projectile/projectile_for_player.tscn"), # Corrected file path
		"projectile_for_player_2": preload("res://Scenes/Projectile/projectile_for_player_2.tscn"), # Corrected file path
		"projectile_test_for_enemy": preload("res://Scenes/Projectile/projectile_for_enemy1.tscn"), # Corrected file path
		"projectile_bomb": preload("res://Scenes/Projectile/Projectile_bomb/projectile_bomb.tscn"), # Corrected file path
	}
}
# Rarity weight curves to influence upgrade selection based on player level
const RARITY_CURVES = {
	"common": {
		"color": "00bfff", #blue
		"base_weight": 100.0,
		"level_modifier": -10  # Decreases as level increases
	},
	"rare": {
		"color": "00ff00", #green
		"base_weight": 0.0,
		"level_modifier": 5  # Increases slightly with level
	},
	"epic": {
		"color": "9400d3", #purple
		"base_weight": 0.0,
		"level_modifier": 5  # Increases with level
	}
}

# Upgrades 117,guns 9
const DEFAULT_UPGRADE = "Heal_health"
# Each upgrade has a name, description, associated functions to call, 
# arguments for the functions, rarity and the icon path
const UPGRADES = {
	# Guns
	"Futuristic Chicago": {
		"displayname": "Futuristic Chicago",
		"details": "Adds Futuristic Chicago gun in your arsenal.",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Armas_E_Personagens/1 Icons/futuristic_chicago.png",
		"functions": ["add_gun"],
		"arguments": [["Futuristic Chicago"]],
	},
	"Rocket Launcher": {
		"displayname": "Rocket Launcher",
		"details": "Adds Rocket Launcher gun in your arsenal.",
		"rarity": "epic",
		"icon": "res://Assets/Textures/Armas_E_Personagens/1 Icons/rocket_launcher.png",
		"functions": ["add_gun"],
		"arguments": [["Rocket Launcher"]],
	},
	"Desert Sniper": {
		"displayname": "Desert Sniper",
		"details": "Adds Desert Sniper gun in your arsenal.",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Armas_E_Personagens/1 Icons/desert_sniper.png",
		"functions": ["add_gun"],
		"arguments": [["Desert Sniper"]],
	},
	"M45": {
		"displayname": "M45",
		"details": "Adds M45 gun in your arsenal.",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Armas_E_Personagens/1 Icons/m45.png",
		"functions": ["add_gun"],
		"arguments": [["M45"]],
	},
	"F547": {
		"displayname": "F547",
		"details": "Adds F547 gun in your arsenal.",
		"rarity": "epic",
		"icon": "res://Assets/Textures/Armas_E_Personagens/1 Icons/f547.png",
		"functions": ["add_gun"],
		"arguments": [["F547"]],
	},
	"K6554": {
		"displayname": "K6554",
		"details": "Adds K6554 gun in your arsenal.",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Armas_E_Personagens/1 Icons/k6554.png",
		"functions": ["add_gun"],
		"arguments": [["K6554"]],
	},
	"RRR7": {
		"displayname": "RRR7",
		"details": "Adds RRR7 gun in your arsenal.",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Armas_E_Personagens/1 Icons/rrr7.png",
		"functions": ["add_gun"],
		"arguments": [["RRR7"]],
	},
	"T58": {
		"displayname": "T58",
		"details": "Adds T58 gun in your arsenal.",
		"rarity": "epic",
		"icon": "res://Assets/Textures/Armas_E_Personagens/1 Icons/t58.png",
		"functions": ["add_gun"],
		"arguments": [["T58"]],
	},
	"G65": {
		"displayname": "G65",
		"details": "Adds G65 gun in your arsenal.",
		"rarity": "epic",
		"icon": "res://Assets/Textures/Armas_E_Personagens/1 Icons/g65.png",
		"functions": ["add_gun"],
		"arguments": [["G65"]],
	},


	# Upgrades
	"Agile_Body": {
		"displayname": "Agile Body",
		"details": "Movement speed: [color=#00ff00]+15%[/color]. Max health: [color=#ff0000]-10[/color] points.",
		"rarity": "common",
		"icon": "res://Assets/Textures/GUI/icons/1 Icons/10/Skillicon10_29.png",
		"functions": ["update_player_velocity", "update_max_health"],
		"arguments": [[0.15], [-10]],
	},

	"Heavy_Armor": {
		"displayname": "Heavy Armor",
		"details": "Max health: [color=#00ff00]+25[/color]. Movement speed: [color=#ff0000]-10%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/black_armor_torso.png",
		"functions": ["update_max_health", "update_player_velocity"],
		"arguments": [[25], [-0.10]],
	},

	"Sharpened_Ammo": {
		"displayname": "Sharpened Ammo",
		"details": "Bullet damage: [color=#00ff00]+10%[/color]. Fire rate: [color=#ff0000]-10%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/ion_core.png",
		"functions": ["update_guns", "update_guns"],
		"arguments": [["damage", 0.10], ["fire_rate", -0.10]],
	},
	"Heal_health": {
		"displayname": "Health Pack",
		"details": "Heals the player by [color=#00ff00]+10[/color] health points.",
		"rarity": "common",
		"icon": "res://Assets/Textures/GUI/icons/1 Icons/6/Skillicon6_16.png",
		"functions": ["heal_player"],
		"arguments": [[10]],
	},

	"Overclocked_Guns": {
		"displayname": "Overclocked Guns",
		"details": "Fire rate: [color=#00ff00]+20%[/color]. Projectile speed: [color=#ff0000]-15%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/GUI/icons/1 Icons/1/Skillicon1_17.png",
		"functions": ["update_guns", "update_guns"],
		"arguments": [["fire_rate", 0.20], ["projectile_speed", -0.15]],
	},

	"Reinforced_Bullets": {
		"displayname": "Reinforced Bullets",
		"details": "Damage: [color=#00ff00]+25%[/color]. Knockback: [color=#ff0000]-20%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/reinforced_bullets.png",
		"functions": ["update_guns", "update_guns"],
		"arguments": [["damage", 0.25], ["knockback_amount", -0.20]],
	},

	"Cool_Glasses": {
		"displayname": "Cool Glasses",
		"details": "Projectile range: [color=#00ff00]+30%[/color]. Fire rate: [color=#ff0000]-15%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/cool_glasses.png",
		"functions": ["update_guns", "update_guns"],
		"arguments": [["fire_range", 0.30], ["fire_rate", -0.15]],
	},

	"Pierce": {
		"displayname": "Pierce",
		"details": "Pierce: [color=#00ff00]+2[/color]. Projectile speed: [color=#ff0000]-20%[/color].",
		"rarity": "epic",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/cow_nose_ring.png",
		"functions": ["update_guns", "update_guns"],
		"arguments": [["pierce", 2], ["projectile_speed", -0.20]],
	},

	"Glass_Cannon": {
		"displayname": "Glass Cannon",
		"details": "Damage: [color=#00ff00]+40%[/color]. Max health: [color=#ff0000]-30[/color] points.",
		"rarity": "epic",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/glass_cannon-removebg-preview.png",
		"functions": ["update_guns", "update_max_health"],
		"arguments": [["damage", 0.40], [-30]],
	},

	"Steroid": {
		"displayname": "Steroid",
		"details": "Max health: [color=#00ff00]+50[/color]. Knockback: [color=#00ff00]+30%[/color]. Movement speed: [color=#ff0000]-20%[/color].",
		"rarity": "epic",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/steroid.png",
		"functions": ["update_max_health", "update_guns", "update_player_velocity"],
		"arguments": [[50], ["knockback_amount", 0.30], [-0.20]],
	},

	"Anti_Radiation_Pills": {
		"displayname": "Anti-Radiation Pills",
		"details": "Heals the player by [color=#00ff00]+25[/color] health points.",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/anti_radiation_pills.png",
		"functions": ["heal_player"],
		"arguments": [[25]],
	},

	"Arc_Core": {
		"displayname": "Arc Core",
		"details": "Bullet damage: [color=#00ff00]+10%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/arc_core.png",
		"functions": ["update_guns"],
		"arguments": [["damage", 0.10]],
	},

	"Arc_Glyph": {
		"displayname": "Arc Glyph",
		"details": "Fire rate: [color=#00ff00]+12%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/arc_glyph.png",
		"functions": ["update_guns"],
		"arguments": [["fire_rate", 0.12]],
	},

	"Arc_Relic": {
		"displayname": "Arc Relic",
		"details": "Max health: [color=#00ff00]+15[/color] points.",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/arc_relic.png",
		"functions": ["update_max_health"],
		"arguments": [[15]],
	},

	"Astronaut_Head": {
		"displayname": "Astronaut Head",
		"details": "Max health: [color=#00ff00]+20[/color]. Movement speed: [color=#ff0000]-5%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/astronaut_head.png",
		"functions": ["update_max_health", "update_player_velocity"],
		"arguments": [[20], [-0.05]],
	},

	"Black_Armor_Boot": {
		"displayname": "Black Armor Boot",
		"details": "Max health: [color=#00ff00]+20[/color]. Movement speed: [color=#ff0000]-10%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/black_armor_boot.png",
		"functions": ["update_max_health", "update_player_velocity"],
		"arguments": [[20], [-0.10]],
	},

	"Black_Armor_Gloves": {
		"displayname": "Black Armor Gloves",
		"details": "Knockback: [color=#00ff00]+15%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/black_armor_gloves.png",
		"functions": ["update_guns"],
		"arguments": [["knockback_amount", 0.15]],
	},

	"Black_Backpack": {
		"displayname": "Black Backpack",
		"details": "Movement speed: [color=#00ff00]+5%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/black_backpack.png",
		"functions": ["update_player_velocity"],
		"arguments": [[0.05]],
	},

	"Black_EPI_Gloves": {
		"displayname": "Black EPI Gloves",
		"details": "Fire rate: [color=#00ff00]+10%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/black_epi_gloves.png",
		"functions": ["update_guns"],
		"arguments": [["fire_rate", 0.10]],
	},

	"Black_EPI": {
		"displayname": "Black EPI",
		"details": "Max health: [color=#00ff00]+10[/color]. Bullet damage: [color=#00ff00]+5%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/black_epi.png",
		"functions": ["update_max_health", "update_guns"],
		"arguments": [[10], ["damage", 0.05]],
	},

	"Black_EPI_Torso": {
		"displayname": "Black EPI Torso",
		"details": "Max health: [color=#00ff00]+25[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/black_epi_torso.png",
		"functions": ["update_max_health"],
		"arguments": [[25]],
	},

	"Black_Gas_Mask": {
		"displayname": "Black Gas Mask",
		"details": "Max health: [color=#00ff00]+10[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/black_gas_mask.png",
		"functions": ["update_max_health"],
		"arguments": [[10]],
	},

	"Black_Robot_Head": {
		"displayname": "Black Robot Head",
		"details": "Projectile speed: [color=#00ff00]+15%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/black_robot_head.png",
		"functions": ["update_guns"],
		"arguments": [["projectile_speed", 0.15]],
	},

	"Chip": {
		"displayname": "Chip",
		"details": "Fire rate: [color=#00ff00]+8%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/chip.png",
		"functions": ["update_guns"],
		"arguments": [["fire_rate", 0.08]],
	},

	"Cool_Glasses_Mk2": {
		"displayname": "Cool Glasses MK2",
		"details": "Projectile range: [color=#00ff00]+20%[/color]. Fire rate: [color=#ff0000]-10%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/cool_glasses.png",
		"functions": ["update_guns", "update_guns"],
		"arguments": [["fire_range", 0.20], ["fire_rate", -0.10]],
	},

	"Crimson_Fragment_1": {
		"displayname": "Crimson Fragment I",
		"details": "Bullet damage: [color=#00ff00]+8%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/crimson_fragment_1.png",
		"functions": ["update_guns"],
		"arguments": [["damage", 0.08]],
	},

	"Crimson_Fragment": {
		"displayname": "Crimson Fragment",
		"details": "Movement speed: [color=#00ff00]+5%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/crimson_fragment.png",
		"functions": ["update_player_velocity"],
		"arguments": [[0.05]],
	},

	"Crimson_Glyph": {
		"displayname": "Crimson Glyph",
		"details": "Projectile speed: [color=#00ff00]+15%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/crimson_glyph.png",
		"functions": ["update_guns"],
		"arguments": [["projectile_speed", 0.15]],
	},
	"Crimson_Relic_1": {
		"displayname": "Crimson Relic I",
		"details": "Bullet damage: [color=#00ff00]+12%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/crimson_relic_1.png",
		"functions": ["update_guns"],
		"arguments": [["damage", 0.12]],
	},
	"Crimson_Relic": {
		"displayname": "Crimson Relic",
		"details": "Bullet damage: [color=#00ff00]+18%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/crimson_relic.png",
		"functions": ["update_guns"],
		"arguments": [["damage", 0.18]],
	},
	"Crimson_Sphere": {
		"displayname": "Crimson Sphere",
		"details": "Projectile speed: [color=#00ff00]+20%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/crimson_sphere.png",
		"functions": ["update_guns"],
		"arguments": [["projectile_speed", 0.20]],
	},
	"Cyber_Glyph": {
		"displayname": "Cyber Glyph",
		"details": "Fire rate: [color=#00ff00]+10%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/cyber_glyph.png",
		"functions": ["update_guns"],
		"arguments": [["fire_rate", 0.10]],
	},
	"Cyber_Plate": {
		"displayname": "Cyber Plate",
		"details": "Max health: [color=#00ff00]+25[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/cyber_plate.png",
		"functions": ["update_max_health"],
		"arguments": [[25]],
	},
	"Cyber_Relic": {
		"displayname": "Cyber Relic",
		"details": "Bullet damage: [color=#00ff00]+15%[/color]. Fire rate: [color=#ff0000]-5%[/color].",
		"rarity": "epic",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/cyber_relic.png",
		"functions": ["update_guns", "update_guns"],
		"arguments": [["damage", 0.15], ["fire_rate", -0.05]],
	},
	"Ember_Glyph_1": {
		"displayname": "Ember Glyph I",
		"details": "Bullet damage: [color=#00ff00]+8%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/ember_glyph_1.png",
		"functions": ["update_guns"],
		"arguments": [["damage", 0.08]],
	},
	"Ember_Glyph": {
		"displayname": "Ember Glyph",
		"details": "Projectile speed: [color=#00ff00]+15%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/ember_glyph.png",
		"functions": ["update_guns"],
		"arguments": [["projectile_speed", 0.15]],
	},
	"Ember_Relic_1": {
		"displayname": "Ember Relic I",
		"details": "Knockback: [color=#00ff00]+20%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/ember_relic_1.png",
		"functions": ["update_guns"],
		"arguments": [["knockback_amount", 0.20]],
	},
	"Ember_Relic_2": {
		"displayname": "Ember Relic II",
		"details": "Explosion size: [color=#00ff00]+25%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/ember_relic_2.png",
		"functions": ["update_guns"],
		"arguments": [["explosion_size", 1.25]],
	},
	"Ember_Relic": {
		"displayname": "Ember Relic",
		"details": "Fire rate: [color=#00ff00]+20%[/color]. Projectile speed: [color=#00ff00]+10%[/color].",
		"rarity": "epic",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/ember_relic.png",
		"functions": ["update_guns", "update_guns"],
		"arguments": [["fire_rate", 0.20], ["projectile_speed", 0.10]],
	},
	"Epi_2_Head": {
		"displayname": "EPI II Head",
		"details": "Max health: [color=#00ff00]+15[/color]. Movement speed: [color=#ff0000]-5%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/epi_2_head.png",
		"functions": ["update_max_health", "update_player_velocity"],
		"arguments": [[15], [-0.05]],
	},
	"Epi_Head": {
		"displayname": "EPI Head",
		"details": "Max health: [color=#00ff00]+10[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/epi_head.png",
		"functions": ["update_max_health"],
		"arguments": [[10]],
	},
	"Flare_Fragment": {
		"displayname": "Flare Fragment",
		"details": "Projectile speed: [color=#00ff00]+10%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/flare_fragment.png",
		"functions": ["update_guns"],
		"arguments": [["projectile_speed", 0.10]],
	},
	"Freezer_Serpentine": {
		"displayname": "Freezer Serpentine",
		"details": "Fire rate: [color=#00ff00]+12%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/freezer_serpentine.png",
		"functions": ["update_guns"],
		"arguments": [["fire_rate", 0.12]],
	},
	"Gas_Mask_2": {
		"displayname": "Gas Mask II",
		"details": "Max health: [color=#00ff00]+12[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/gas_mask_2.png",
		"functions": ["update_max_health"],
		"arguments": [[12]],
	},
	"Gas_Mask_3": {
		"displayname": "Gas Mask III",
		"details": "Max health: [color=#00ff00]+20[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/gas_mask_3.png",
		"functions": ["update_max_health"],
		"arguments": [[20]],
	},
	"Gloom_Fragment": {
		"displayname": "Gloom Fragment",
		"details": "Bullet damage: [color=#00ff00]+6%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/gloom_fragment.png",
		"functions": ["update_guns"],
		"arguments": [["damage", 0.06]],
	},
	"Gloom_Glyph": {
		"displayname": "Gloom Glyph",
		"details": "Projectile speed: [color=#00ff00]+12%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/gloom_glyph.png",
		"functions": ["update_guns"],
		"arguments": [["projectile_speed", 0.12]],
	},
	"Gloom_Orb": {
		"displayname": "Gloom Orb",
		"details": "Damage: [color=#00ff00]+20%[/color]. Max health: [color=#ff0000]-10[/color] points.",
		"rarity": "epic",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/gloom_orb.png",
		"functions": ["update_guns", "update_max_health"],
		"arguments": [["damage", 0.20], [-10]],
	},
	"Green_EPI_Boot": {
		"displayname": "Green EPI Boot",
		"details": "Movement speed: [color=#00ff00]+8%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/green_epi_boot.png",
		"functions": ["update_player_velocity"],
		"arguments": [[0.08]],
	},
	"Green_EPI_Gloves": {
		"displayname": "Green EPI Gloves",
		"details": "Fire rate: [color=#00ff00]+10%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/green_epi_gloves.png",
		"functions": ["update_guns"],
		"arguments": [["fire_rate", 0.10]],
	},
	"Green_EPI_Torso": {
		"displayname": "Green EPI Torso",
		"details": "Max health: [color=#00ff00]+28[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/green_epi_torso.png",
		"functions": ["update_max_health"],
		"arguments": [[28]],
	},
	"Green_Gas_Container": {
		"displayname": "Green Gas Container",
		"details": "Max health: [color=#00ff00]+12[/color]. Movement speed: [color=#00ff00]+3%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/green_gas_container.png",
		"functions": ["update_max_health", "update_player_velocity"],
		"arguments": [[12], [0.03]],
	},
	"Ignition_Fragment": {
		"displayname": "Ignition Fragment",
		"details": "Bullet damage: [color=#00ff00]+10%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/ignition_fragment.png",
		"functions": ["update_guns"],
		"arguments": [["damage", 0.10]],
	},
	"Ignition_Glyph": {
		"displayname": "Ignition Glyph",
		"details": "Fire rate: [color=#00ff00]+14%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/ignition_glyph.png",
		"functions": ["update_guns"],
		"arguments": [["fire_rate", 0.14]],
	},
	"Ion_Coil": {
		"displayname": "Ion Coil",
		"details": "Projectile speed: [color=#00ff00]+18%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/ion_coil.png",
		"functions": ["update_guns"],
		"arguments": [["projectile_speed", 0.18]],
	},
	"Ion_Core": {
		"displayname": "Ion Core",
		"details": "Bullet damage: [color=#00ff00]+12%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/ion_core.png",
		"functions": ["update_guns"],
		"arguments": [["damage", 0.12]],
	},
	"Ion_Fragment": {
		"displayname": "Ion Fragment",
		"details": "Projectile speed: [color=#00ff00]+10%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/ion_fragment.png",
		"functions": ["update_guns"],
		"arguments": [["projectile_speed", 0.10]],
	},
	"Ion_Glyph_1": {
		"displayname": "Ion Glyph I",
		"details": "Fire rate: [color=#00ff00]+8%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/ion_glyph_1.png",
		"functions": ["update_guns"],
		"arguments": [["fire_rate", 0.08]],
	},
	"Ion_Glyph": {
		"displayname": "Ion Glyph",
		"details": "Fire rate: [color=#00ff00]+16%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/ion_glyph.png",
		"functions": ["update_guns"],
		"arguments": [["fire_rate", 0.16]],
	},
	"Ion_Sphere": {
		"displayname": "Ion Sphere",
		"details": "Projectile speed: [color=#00ff00]+22%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/ion_sphere.png",
		"functions": ["update_guns"],
		"arguments": [["projectile_speed", 0.22]],
	},
	"Iron_Fragment": {
		"displayname": "Iron Fragment",
		"details": "Bullet damage: [color=#00ff00]+6%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/iron_fragment.png",
		"functions": ["update_guns"],
		"arguments": [["damage", 0.06]],
	},
	"Iron_Ingot": {
		"displayname": "Iron Ingot",
		"details": "Max health: [color=#00ff00]+18[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/iron_ingot.png",
		"functions": ["update_max_health"],
		"arguments": [[18]],
	},
	"Multidimencional_Cube": {
		"displayname": "Multidimensional Cube",
		"details": "Damage: [color=#00ff00]+25%[/color]. Projectile speed: [color=#00ff00]+12%[/color].",
		"rarity": "epic",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/multidimencional_cube.png",
		"functions": ["update_guns", "update_guns"],
		"arguments": [["damage", 0.25], ["projectile_speed", 0.12]],
	},
	"Old_Gas_Mask": {
		"displayname": "Old Gas Mask",
		"details": "Max health: [color=#00ff00]+8[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/old_gas_mask.png",
		"functions": ["update_max_health"],
		"arguments": [[8]],
	},
	"One_Side_Gas_Mask": {
		"displayname": "One-Side Gas Mask",
		"details": "Movement speed: [color=#00ff00]+6%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/one_side_gas_mask.png",
		"functions": ["update_player_velocity"],
		"arguments": [[0.06]],
	},
	"Orange_Candle": {
		"displayname": "Orange Candle",
		"details": "Fire rate: [color=#00ff00]+12%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/orange_candle.png",
		"functions": ["update_guns"],
		"arguments": [["fire_rate", 0.12]],
	},
	"Overdrive_Fragment": {
		"displayname": "Overdrive Fragment",
		"details": "Bullet damage: [color=#00ff00]+9%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/overdrive_fragment.png",
		"functions": ["update_guns"],
		"arguments": [["damage", 0.09]],
	},
	"Overdrive_Glyph_1": {
		"displayname": "Overdrive Glyph I",
		"details": "Fire rate: [color=#00ff00]+10%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/overdrive_glyph_1.png",
		"functions": ["update_guns"],
		"arguments": [["fire_rate", 0.10]],
	},
	"Overdrive_Orb": {
		"displayname": "Overdrive Orb",
		"details": "Damage: [color=#00ff00]+12%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/overdrive_orb.png",
		"functions": ["update_guns"],
		"arguments": [["damage", 0.12]],
	},
	"Overdrive_Relic": {
		"displayname": "Overdrive Relic",
		"details": "Damage: [color=#00ff00]+20%[/color]. Fire rate: [color=#ff0000]-5%[/color].",
		"rarity": "epic",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/overdrive_relic.png",
		"functions": ["update_guns", "update_guns"],
		"arguments": [["damage", 0.20], ["fire_rate", -0.05]],
	},
	"Overdrive_Sphere": {
		"displayname": "Overdrive Sphere",
		"details": "Projectile speed: [color=#00ff00]+18%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/overdrive_sphere.png",
		"functions": ["update_guns"],
		"arguments": [["projectile_speed", 0.18]],
	},
	"Phase_Fragment": {
		"displayname": "Phase Fragment",
		"details": "Projectile speed: [color=#00ff00]+10%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/phase_fragment.png",
		"functions": ["update_guns"],
		"arguments": [["projectile_speed", 0.10]],
	},
	"Plutonium": {
		"displayname": "Plutonium",
		"details": "Max health: [color=#00ff00]+30[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/plutonium.png",
		"functions": ["update_max_health"],
		"arguments": [[30]],
	},
	"Prism_Core": {
		"displayname": "Prism Core",
		"details": "Bullet damage: [color=#00ff00]+14%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/prism_core.png",
		"functions": ["update_guns"],
		"arguments": [["damage", 0.14]],
	},
	"Prism_Fragment_1": {
		"displayname": "Prism Fragment I",
		"details": "Bullet damage: [color=#00ff00]+8%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/prism_fragment_1.png",
		"functions": ["update_guns"],
		"arguments": [["damage", 0.08]],
	},
	"Prism_Fragment_2": {
		"displayname": "Prism Fragment II",
		"details": "Projectile speed: [color=#00ff00]+12%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/prism_fragment_2.png",
		"functions": ["update_guns"],
		"arguments": [["projectile_speed", 0.12]],
	},
	"Prism_Fragment": {
		"displayname": "Prism Fragment",
		"details": "Movement speed: [color=#00ff00]+6%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/prism_fragment.png",
		"functions": ["update_player_velocity"],
		"arguments": [[0.06]],
	},
	"Prism_Glyph_1": {
		"displayname": "Prism Glyph I",
		"details": "Fire rate: [color=#00ff00]+8%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/prism_glyph_1.png",
		"functions": ["update_guns"],
		"arguments": [["fire_rate", 0.08]],
	},
	"Prism_Glyph": {
		"displayname": "Prism Glyph",
		"details": "Fire rate: [color=#00ff00]+16%[/color]. Projectile speed: [color=#00ff00]+8%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/prism_glyph.png",
		"functions": ["update_guns", "update_guns"],
		"arguments": [["fire_rate", 0.16], ["projectile_speed", 0.08]],
	},
	"Prism_Module": {
		"displayname": "Prism Module",
		"details": "Damage: [color=#00ff00]+22%[/color].",
		"rarity": "epic",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/prism_module.png",
		"functions": ["update_guns"],
		"arguments": [["damage", 0.22]],
	},
	"Prism_Relic": {
		"displayname": "Prism Relic",
		"details": "Projectile speed: [color=#00ff00]+25%[/color].",
		"rarity": "epic",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/prism_relic.png",
		"functions": ["update_guns"],
		"arguments": [["projectile_speed", 0.25]],
	},
	"Psi_Glyph": {
		"displayname": "Psi Glyph",
		"details": "Fire rate: [color=#00ff00]+10%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/psi_glyph.png",
		"functions": ["update_guns"],
		"arguments": [["fire_rate", 0.10]],
	},
	"Psi_Orb": {
		"displayname": "Psi Orb",
		"details": "Damage: [color=#00ff00]+12%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/psi_orb.png",
		"functions": ["update_guns"],
		"arguments": [["damage", 0.12]],
	},
	"Psi_Relic": {
		"displayname": "Psi Relic",
		"details": "Pierce: [color=#00ff00]+2[/color]. Projectile speed: [color=#00ff00]+10%[/color].",
		"rarity": "epic",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/psi_relic.png",
		"functions": ["update_guns", "update_guns"],
		"arguments": [["pierce", 2], ["projectile_speed", 0.10]],
	},
	"Pulse_Glyph_1": {
		"displayname": "Pulse Glyph I",
		"details": "Fire rate: [color=#00ff00]+8%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/pulse_glyph_1.png",
		"functions": ["update_guns"],
		"arguments": [["fire_rate", 0.08]],
	},
	"Pulse_Glyph_2": {
		"displayname": "Pulse Glyph II",
		"details": "Fire rate: [color=#00ff00]+12%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/pulse_glyph_2.png",
		"functions": ["update_guns"],
		"arguments": [["fire_rate", 0.12]],
	},

	"Pulse_Glyph": {
		"displayname": "Pulse Glyph",
		"details": "Fire rate: [color=#00ff00]+10%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/pulse_glyph.png",
		"functions": ["update_guns"],
		"arguments": [["fire_rate", 0.10]],
	},

	"Pulse_Sphere": {
		"displayname": "Pulse Sphere",
		"details": "Projectile speed: [color=#00ff00]+18%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/pulse_sphere.png",
		"functions": ["update_guns"],
		"arguments": [["projectile_speed", 0.18]],
	},

	"Quantum_Fragment_1": {
		"displayname": "Quantum Fragment I",
		"details": "Bullet damage: [color=#00ff00]+8%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/quantum_fragment_1.png",
		"functions": ["update_guns"],
		"arguments": [["damage", 0.08]],
	},

	"Quantum_Fragment": {
		"displayname": "Quantum Fragment",
		"details": "Projectile speed: [color=#00ff00]+12%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/quantum_fragment.png",
		"functions": ["update_guns"],
		"arguments": [["projectile_speed", 0.12]],
	},

	"Quantum_Glyph": {
		"displayname": "Quantum Glyph",
		"details": "Fire rate: [color=#00ff00]+14%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/quantum_glyph.png",
		"functions": ["update_guns"],
		"arguments": [["fire_rate", 0.14]],
	},

	"Quantum_Item": {
		"displayname": "Quantum Item",
		"details": "Damage: [color=#00ff00]+12%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/quantum_item.png",
		"functions": ["update_guns"],
		"arguments": [["damage", 0.12]],
	},

	"Quantum_Relic_1": {
		"displayname": "Quantum Relic I",
		"details": "Bullet damage: [color=#00ff00]+15%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/quantum_relic_1.png",
		"functions": ["update_guns"],
		"arguments": [["damage", 0.15]],
	},

	"Quantum_Relic": {
		"displayname": "Quantum Relic",
		"details": "Damage: [color=#00ff00]+25%[/color]. Fire rate: [color=#ff0000]-10%[/color].",
		"rarity": "epic",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/quantum_relic.png",
		"functions": ["update_guns", "update_guns"],
		"arguments": [["damage", 0.25], ["fire_rate", -0.10]],
	},

	"Quantum_Sphere": {
		"displayname": "Quantum Sphere",
		"details": "Projectile speed: [color=#00ff00]+20%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/quantum_sphere.png",
		"functions": ["update_guns"],
		"arguments": [["projectile_speed", 0.20]],
	},

	"Radiation_Core": {
		"displayname": "Radiation Core",
		"details": "Max health: [color=#00ff00]+20[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/radiation_core.png",
		"functions": ["update_max_health"],
		"arguments": [[20]],
	},

	"Radiation_Detector_2": {
		"displayname": "Radiation Detector II",
		"details": "Movement speed: [color=#00ff00]+5%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/radiation_detector_2.png",
		"functions": ["update_player_velocity"],
		"arguments": [[0.05]],
	},

	"Radiative_Residue": {
		"displayname": "Radiative Residue",
		"details": "Bullet damage: [color=#00ff00]+10%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/radiative_residue.png",
		"functions": ["update_guns"],
		"arguments": [["damage", 0.10]],
	},

	"Radiator_Detector_3": {
		"displayname": "Radiator Detector III",
		"details": "Max health: [color=#00ff00]+12[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/radiator_detector_3.png",
		"functions": ["update_max_health"],
		"arguments": [[12]],
	},

	"Radiator_Detector_4": {
		"displayname": "Radiator Detector IV",
		"details": "Max health: [color=#00ff00]+18[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/radiator_detector_4.png",
		"functions": ["update_max_health"],
		"arguments": [[18]],
	},

	"Radiator_Detector": {
		"displayname": "Radiator Detector",
		"details": "Movement speed: [color=#00ff00]+4%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/radiator_detector.png",
		"functions": ["update_player_velocity"],
		"arguments": [[0.04]],
	},

	"Rift_Glyph_1": {
		"displayname": "Rift Glyph I",
		"details": "Fire rate: [color=#00ff00]+8%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/rift_glyph_1.png",
		"functions": ["update_guns"],
		"arguments": [["fire_rate", 0.08]],
	},

	"Rift_Glyph": {
		"displayname": "Rift Glyph",
		"details": "Projectile speed: [color=#00ff00]+15%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/rift_glyph.png",
		"functions": ["update_guns"],
		"arguments": [["projectile_speed", 0.15]],
	},

	"Shovel": {
		"displayname": "Shovel",
		"details": "Max health: [color=#00ff00]+6[/color]. Movement speed: [color=#00ff00]+3%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/shovel.png",
		"functions": ["update_max_health", "update_player_velocity"],
		"arguments": [[6], [0.03]],
	},

	"Signal_Core": {
		"displayname": "Signal Core",
		"details": "Bullet damage: [color=#00ff00]+12%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/signal_core.png",
		"functions": ["update_guns"],
		"arguments": [["damage", 0.12]],
	},

	"Signal_Fragment_1": {
		"displayname": "Signal Fragment I",
		"details": "Fire rate: [color=#00ff00]+8%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/signal_fragment_1.png",
		"functions": ["update_guns"],
		"arguments": [["fire_rate", 0.08]],
	},
	"Signal_Fragment": {
		"displayname": "Signal Fragment",
		"details": "Fire rate: [color=#00ff00]+8%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/signal_fragment.png",
		"functions": ["update_guns"],
		"arguments": [["fire_rate", 0.08]],
	},
	"Signal_Glyph_1": {
		"displayname": "Signal Glyph I",
		"details": "Fire rate: [color=#00ff00]+8%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/signal_glyph_1.png",
		"functions": ["update_guns"],
		"arguments": [["fire_rate", 0.08]],
	},
	"Signal_Glyph_2": {
		"displayname": "Signal Glyph II",
		"details": "Fire rate: [color=#00ff00]+12%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/signal_glyph_2.png",
		"functions": ["update_guns"],
		"arguments": [["fire_rate", 0.12]],
	},
	"Signal_Glyph": {
		"displayname": "Signal Glyph",
		"details": "Fire rate: [color=#00ff00]+10%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/signal_glyph.png",
		"functions": ["update_guns"],
		"arguments": [["fire_rate", 0.10]],
	},
	"Signal_Relic_1": {
		"displayname": "Signal Relic I",
		"details": "Damage: [color=#00ff00]+12%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/signal_relic_1.png",
		"functions": ["update_guns"],
		"arguments": [["damage", 0.12]],
	},
	"Signal_Relic_2": {
		"displayname": "Signal Relic II",
		"details": "Damage: [color=#00ff00]+18%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/signal_relic_2.png",
		"functions": ["update_guns"],
		"arguments": [["damage", 0.18]],
	},
	"Signal_Relic": {
		"displayname": "Signal Relic",
		"details": "Damage: [color=#00ff00]+22%[/color]. Fire rate: [color=#ff0000]-5%[/color].",
		"rarity": "epic",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/signal_relic.png",
		"functions": ["update_guns", "update_guns"],
		"arguments": [["damage", 0.22], ["fire_rate", -0.05]],
	},
	"Signal_Unit": {
		"displayname": "Signal Unit",
		"details": "Max health: [color=#00ff00]+15[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/signal_unit.png",
		"functions": ["update_max_health"],
		"arguments": [[15]],
	},
	"Uranium": {
		"displayname": "Uranium",
		"details": "Max health: [color=#00ff00]+35[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/uranium.png",
		"functions": ["update_max_health"],
		"arguments": [[35]],
	},
	"Verdant_Glyph": {
		"displayname": "Verdant Glyph",
		"details": "Movement speed: [color=#00ff00]+5%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/verdant_glyph.png",
		"functions": ["update_player_velocity"],
		"arguments": [[0.05]],
	},
	"Void_Fragment": {
		"displayname": "Void Fragment",
		"details": "Damage: [color=#00ff00]+7%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/void_fragment.png",
		"functions": ["update_guns"],
		"arguments": [["damage", 0.07]],
	},
	"Void_Item": {
		"displayname": "Void Item",
		"details": "Damage: [color=#00ff00]+16%[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/void_item.png",
		"functions": ["update_guns"],
		"arguments": [["damage", 0.16]],
	},
	"Void_Relic_1": {
		"displayname": "Void Relic I",
		"details": "Pierce: [color=#00ff00]+1[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/void_relic_1.png",
		"functions": ["update_guns"],
		"arguments": [["pierce", 1]],
	},
	"Void_Relic": {
		"displayname": "Void Relic",
		"details": "Pierce: [color=#00ff00]+2[/color]. Projectile speed: [color=#00ff00]+12%[/color].",
		"rarity": "epic",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/void_relic.png",
		"functions": ["update_guns", "update_guns"],
		"arguments": [["pierce", 2], ["projectile_speed", 0.12]],
	},
	"Yellow_EPI_Boot": {
		"displayname": "Yellow EPI Boot",
		"details": "Movement speed: [color=#00ff00]+7%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/yellow_epi_boot.png",
		"functions": ["update_player_velocity"],
		"arguments": [[0.07]],
	},
	"Yellow_EPI_Gloves": {
		"displayname": "Yellow EPI Gloves",
		"details": "Fire rate: [color=#00ff00]+10%[/color].",
		"rarity": "common",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/yellow_epi_gloves.png",
		"functions": ["update_guns"],
		"arguments": [["fire_rate", 0.10]],
	},
	"Yellow_EPI": {
		"displayname": "Yellow EPI",
		"details": "Max health: [color=#00ff00]+22[/color].",
		"rarity": "rare",
		"icon": "res://Assets/Textures/Items/itens/1 Icons/yellow_epi.png",
		"functions": ["update_max_health"],
		"arguments": [[22]],
	}
}
